#!/usr/bin/env python3
"""Regenerate this directory from the source of truth.

The source of truth is the private leaderboard repo (v2d_challenge_leaderboard):

    aggregate/v2d_aggregate.py  ->  aggregator/v2d_aggregate.py
    config/tracks.json          ->  aggregator/tracks.json

Neither file here should be edited by hand. Change the source, then run

    python3 aggregator/resync.py /path/to/v2d_challenge_leaderboard

and commit the result. The copy differs from the source in three mechanical ways, all applied
below, so that the scheduled workflow needs nothing from the private repo:

1. The unused ``v2dlb`` import and its ``sys.path`` hack are removed.
2. ``build_api`` is inlined instead of imported from ``submit/v2d_submit.py`` (which pulls in
   numpy, pandas and the scoring code).
3. The config path points at ``aggregator/tracks.json``, a copy of ``config/tracks.json`` trimmed
   to the fields the aggregator reads (titles, metric list, competition slugs, metric display).
   The full config carries internal paths and rules text that do not belong in a public repo.

Every rewrite must match exactly once. If the source has drifted so that one does not, this
script stops rather than writing a copy that half-applies.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

BUILD_API = '''def build_api():
    """Authenticate with KAGGLE_API_TOKEN (or ~/.kaggle). Inlined from submit/v2d_submit.py."""
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    try:
        api.authenticate()
    except Exception as error:  # noqa: BLE001 - the message matters more than the type
        raise SystemExit(f"Kaggle authentication failed: {error}") from error
    return api


def main() -> int:'''

REWRITES = [
    (
        'sys.path.insert(0, str(Path(__file__).resolve().parents[1]))\n\n'
        'from v2dlb import report_schema as rs\n\n',
        "",
    ),
    (
        'ROOT = Path(__file__).resolve().parents[1]\nCONFIG = ROOT / "config" / "tracks.json"\n',
        'CONFIG = Path(__file__).resolve().parent / "tracks.json"\n',
    ),
    (
        "        from submit.v2d_submit import build_api  # noqa: PLC0415 - only needed online\n\n",
        "",
    ),
    ("def main() -> int:", BUILD_API),
]

HEADER = (
    "# GENERATED by aggregator/resync.py from v2d_challenge_leaderboard/aggregate/v2d_aggregate.py.\n"
    "# Do not edit here; change the source and re-sync. See aggregator/resync.py.\n"
)

TRACK_FIELDS = ("title", "short_title", "metrics", "competitions")


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    source = Path(sys.argv[1]).resolve()

    code = (source / "aggregate" / "v2d_aggregate.py").read_text()
    for old, new in REWRITES:
        count = code.count(old)
        if count != 1:
            raise SystemExit(f"resync: expected 1 match, found {count}, for:\n{old}")
        code = code.replace(old, new)
    shebang, rest = code.split("\n", 1)
    (HERE / "v2d_aggregate.py").write_text(f"{shebang}\n{HEADER}{rest}")

    config = json.loads((source / "config" / "tracks.json").read_text())
    trimmed = {
        "_comment": "GENERATED by aggregator/resync.py from config/tracks.json. Do not edit here.",
        "metric_display": config["metric_display"],
        "tracks": {
            key: {field: spec[field] for field in TRACK_FIELDS if field in spec}
            for key, spec in config["tracks"].items()
        },
    }
    (HERE / "tracks.json").write_text(json.dumps(trimmed, indent=2) + "\n")

    slugs = sum(len(spec["competitions"]) for spec in trimmed["tracks"].values())
    print(f"resync: {len(trimmed['tracks'])} tracks, {slugs} competitions from {source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
