#!/usr/bin/env python3
# GENERATED by aggregator/resync.py from v2d_challenge_leaderboard/aggregate/v2d_aggregate.py.
# Do not edit here; change the source and re-sync. See aggregator/resync.py.
"""Pull every V2D Challenge Kaggle leaderboard and publish one joined JSON per track.

Kaggle gives a competition exactly one score column, so the challenge runs one competition
per metric and this job reassembles them into the multi-column table the site renders.

    python aggregate/v2d_aggregate.py --out build/leaderboard.json
    python aggregate/v2d_aggregate.py --from-dir <dir-of-leaderboard-csvs> --out /tmp/lb.json
    python aggregate/v2d_aggregate.py --out .../leaderboard.json --publish

THE JOIN KEY
------------
``teamId`` is scoped per competition, so one participant entering four competitions gets four
different ids and they cannot be joined on. The leaderboard CSV also carries
``TeamMemberUserNames``, and Kaggle usernames are stable and not participant-editable, so
that is the key: the sorted tuple of member usernames. ``TeamName`` is only a display label
here, because a participant can rename their team independently in each competition and would
then silently appear as two rows.

If a leaderboard export ever lacks ``TeamMemberUserNames`` the job falls back to ``TeamName``
and records that in the output's ``warnings``, so a degraded join is visible rather than
silent.

RAGGED ROWS
-----------
A team that has submitted to three of a track's four competitions gets ``null`` for the
fourth and is listed in ``incomplete``. That is reported rather than hidden: a blank cell is
information, and dropping the team would silently shrink the board.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import os
import subprocess
import sys
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path

CONFIG = Path(__file__).resolve().parent / "tracks.json"

def _metric_meta(config: dict, metric: str) -> dict:
    """Display name and direction for a metric, from config, with a safe default."""
    meta = (config.get("metric_display") or {}).get(metric, {})
    return {
        "display": meta.get("display", metric),
        "higher_is_better": bool(meta.get("higher_is_better", True)),
        "unit": meta.get("unit", ""),
    }

# Kaggle's leaderboard export has used a few header spellings over time; normalise them.
_ALIASES = {
    "rank": "rank",
    "teamid": "team_id",
    "teamname": "team_name",
    "lastsubmissiondate": "submission_date",
    "submissiondate": "submission_date",
    "score": "score",
    "submissioncount": "submission_count",
    "teammemberusernames": "members",
}


def _normalise(row: dict) -> dict:
    out = {}
    for key, value in row.items():
        out[_ALIASES.get(key.strip().lower().replace(" ", ""), key.strip())] = value
    return out


def parse_leaderboard_csv(text: str) -> list[dict]:
    return [_normalise(row) for row in csv.DictReader(io.StringIO(text))]


def read_leaderboard_from_dir(directory: Path, slug: str) -> list[dict] | None:
    """Read a previously downloaded leaderboard, as ``<slug>.csv`` or ``<slug>.zip``."""
    csv_path = directory / f"{slug}.csv"
    if csv_path.exists():
        return parse_leaderboard_csv(csv_path.read_text())
    zip_path = directory / f"{slug}.zip"
    if zip_path.exists():
        with zipfile.ZipFile(zip_path) as archive:
            name = next((n for n in archive.namelist() if n.endswith(".csv")), None)
            if name:
                return parse_leaderboard_csv(archive.read(name).decode("utf-8-sig"))
    return None


def download_leaderboard(api, slug: str) -> list[dict] | None:
    with tempfile.TemporaryDirectory() as tmp:
        try:
            api.competition_leaderboard_download(slug, tmp, quiet=True)
        except Exception as error:  # noqa: BLE001 - one dead board must not kill the run
            print(f"  {slug}: download failed ({type(error).__name__}: {error})", file=sys.stderr)
            return None
        return read_leaderboard_from_dir(Path(tmp), slug)


#: Joins the member usernames into one key. ASCII unit separator rather than a printable
#: character, so no username can ever contain it and be mistaken for two members.
_KEY_SEP = "\x1f"


def team_key(row: dict) -> tuple[str, list[str], bool]:
    """(join key, member usernames, whether the key is the stable one)."""
    members = (row.get("members") or "").strip()
    if members:
        parts = sorted(p.strip() for p in members.replace(";", ",").split(",") if p.strip())
        if parts:
            return (_KEY_SEP.join(parts), parts, True)
    return ((row.get("team_name") or "").strip(), [], False)


def _float(value) -> float | None:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if result == result else None  # drop NaN


def _int(value) -> int | None:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def _reconcile_name_keyed(teams: dict[str, dict]) -> None:
    """Fold a name-keyed entry into its username-keyed twin, in place.

    A leaderboard export that omits TeamMemberUserNames produces a name-keyed entry, which would
    otherwise list the same team twice on the public table. If exactly one username-keyed entry
    displays that name, the two are the same team and are merged; if the name is ambiguous, both
    are left alone, because guessing would be worse than the duplicate.
    """
    stable = {k: e for k, e in teams.items() if e.get("_stable")}
    unstable = {k: e for k, e in teams.items() if not e.get("_stable")}
    if not unstable or not stable:
        return

    def names_of(entry: dict) -> set[str]:
        return {entry["team"], *entry.get("other_names", [])}

    for key, entry in list(unstable.items()):
        candidates = [k for k, e in stable.items() if key in names_of(e)]
        if len(candidates) != 1:
            continue
        target = teams[candidates[0]]
        for field in ("scores", "submission_count", "kaggle_rank"):
            for metric, value in entry[field].items():
                target[field].setdefault(metric, value)
        if entry["last_submission"] and (
            target["last_submission"] is None or entry["last_submission"] > target["last_submission"]
        ):
            target["last_submission"] = entry["last_submission"]
        del teams[key]


def build_track(track: str, spec: dict, boards: dict[str, list[dict] | None], config: dict | None = None) -> dict:
    config = config or {}
    meta = {m: _metric_meta(config, m) for m in spec["metrics"]}
    metrics = [m for m in spec["metrics"] if boards.get(m) is not None]
    unavailable = [m for m in spec["metrics"] if boards.get(m) is None]

    teams: dict[str, dict] = {}
    degraded_join = False
    for metric in metrics:
        for row in boards[metric]:
            key, members, stable = team_key(row)
            if not key:
                continue
            degraded_join = degraded_join or not stable
            entry = teams.setdefault(
                key,
                {
                    "team": row.get("team_name") or key,
                    "members": members,
                    "scores": {},
                    "submission_count": {},
                    "last_submission": None,
                    "kaggle_rank": {},
                    "_stable": stable,
                },
            )
            entry["scores"][metric] = _float(row.get("score"))
            entry["submission_count"][metric] = _int(row.get("submission_count"))
            entry["kaggle_rank"][metric] = _int(row.get("rank"))
            date = (row.get("submission_date") or "").strip()
            if date and (entry["last_submission"] is None or date > entry["last_submission"]):
                entry["last_submission"] = date
            # A team may display a different name per competition. Keep the most recent one
            # and surface the disagreement rather than picking silently.
            name = (row.get("team_name") or "").strip()
            if name and name != entry["team"]:
                entry.setdefault("other_names", [])
                if name not in entry["other_names"]:
                    entry["other_names"].append(name)

    _reconcile_name_keyed(teams)

    rows = []
    incomplete = []
    for key, entry in teams.items():
        entry.pop("_stable", None)
        missing = [m for m in metrics if entry["scores"].get(m) is None]
        if missing:
            entry["missing"] = missing
            incomplete.append({"team": entry["team"], "missing": missing})
        rows.append(entry)

    # Default order: best on the track's first configured metric, blanks last. "Best" follows
    # that metric's direction, because a lower-is-better metric like RPE would otherwise rank
    # the worst entry first. The site lets the reader re-sort by any column, so this is only
    # the initial view.
    primary = metrics[0] if metrics else None
    sign = 1.0 if primary and not meta[primary]["higher_is_better"] else -1.0
    rows.sort(
        key=lambda e: (
            e["scores"].get(primary) is None,
            sign * (e["scores"].get(primary) if e["scores"].get(primary) is not None else 0.0),
            e["team"].lower(),
        )
    )
    for position, entry in enumerate(rows, 1):
        entry["rank"] = position

    warnings = []
    if degraded_join:
        warnings.append(
            "at least one leaderboard export had no TeamMemberUserNames column, so those rows "
            "were joined on the editable team name"
        )
    if unavailable:
        warnings.append(f"no leaderboard data for: {', '.join(unavailable)}")

    return {
        "key": track,
        "title": spec["title"],
        # A tab label. The full title carries the tier description, which is the right thing on
        # a competition page and far too long above a table.
        "short_title": spec.get("short_title", spec["title"]),
        "metrics": [
            {
                "key": m,
                "display": meta[m]["display"],
                "unit": meta[m]["unit"],
                "higher_is_better": meta[m]["higher_is_better"],
                "competition": spec["competitions"][m],
                "available": m in metrics,
            }
            for m in spec["metrics"]
        ],
        "rows": rows,
        "incomplete": incomplete,
        "warnings": warnings,
    }


def material(payload: dict) -> dict:
    """The part of the payload a visitor would notice changing.

    Publishing means a commit in the repository people edit, so it has to be earned. Two kinds of
    difference do not earn one:

    ``generated_at``
        Moves on every run whether or not anything else did.

    ``last_submission``
        Moves whenever a team submits, including when that submission is WORSE than their best.
        Kaggle ranks a team by their best score, so a worse entry leaves every score and every
        position exactly as it was: the table is visually identical and only this date differs.

    The cost is that the "last entry" column can lag behind reality until something that does
    matter changes. That is the intended trade: a stale date is cheaper than a commit per
    submission in a repository humans are working in.
    """
    trimmed = {key: value for key, value in payload.items() if key != "generated_at"}
    for track in trimmed.get("tracks", []):
        for row in track.get("rows", []):
            row.pop("last_submission", None)
    return trimmed


def write_atomic(path: Path, payload: str) -> bool:
    """Write only if the content changed. Returns True when the file was updated.

    Skipping identical writes is what stops the publish step producing ~96 empty commits a day.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == payload:
        return False
    handle, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(payload)
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)
    return True


def publish(repo: Path, relative: Path, message: str) -> None:
    """Commit and push the JSON to the data repo that the challenge page fetches."""
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    env = dict(os.environ)
    env.setdefault("GIT_AUTHOR_NAME", "V2D Leaderboard Bot")
    env.setdefault("GIT_AUTHOR_EMAIL", "v2d_challenge@nvidia.com")
    env.setdefault("GIT_COMMITTER_NAME", env["GIT_AUTHOR_NAME"])
    env.setdefault("GIT_COMMITTER_EMAIL", env["GIT_AUTHOR_EMAIL"])

    def git(*args, check=True):
        return subprocess.run(["git", "-C", str(repo), *args], check=check, capture_output=True, text=True, env=env)

    if git("status", "--porcelain", str(relative)).stdout.strip() == "":
        print("publish: nothing changed")
        return
    git("add", str(relative))
    git("commit", "-m", message)
    push = ["push", "origin", "HEAD"]
    if token:
        push = [
            "-c",
            f"credential.helper=!f(){{ echo username=x-access-token; echo password={token}; }};f",
            *push,
        ]
    result = git(*push, check=False)
    if result.returncode != 0:
        raise SystemExit(f"publish: git push failed:\n{result.stderr}")
    print(f"publish: pushed {relative}")


def build_api():
    """Authenticate with KAGGLE_API_TOKEN (or ~/.kaggle). Inlined from submit/v2d_submit.py."""
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    try:
        api.authenticate()
    except Exception as error:  # noqa: BLE001 - the message matters more than the type
        raise SystemExit(f"Kaggle authentication failed: {error}") from error
    return api


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, required=True, help="path to write leaderboard.json")
    parser.add_argument("--config", type=Path, default=CONFIG)
    parser.add_argument(
        "--from-dir",
        type=Path,
        help="read <slug>.csv / <slug>.zip from this directory instead of calling Kaggle "
        "(used by the offline tests and for replaying a past pull)",
    )
    parser.add_argument("--save-raw", type=Path, help="also keep each downloaded leaderboard CSV here")
    parser.add_argument("--publish", action="store_true", help="git commit and push --out after writing")
    parser.add_argument("--publish-repo", type=Path, help="repo root for --publish (default: --out's repo)")
    parser.add_argument("--now", help="ISO timestamp to stamp into the output (default: current UTC)")
    args = parser.parse_args()

    config = json.loads(args.config.read_text())
    api = None
    if args.from_dir is None:
        api = build_api()

    tracks = []
    for track, spec in config["tracks"].items():
        print(f"{track}:")
        boards: dict[str, list[dict] | None] = {}
        for metric in spec["metrics"]:
            slug = spec["competitions"][metric]
            if args.from_dir is not None:
                board = read_leaderboard_from_dir(args.from_dir, slug)
                if board is None:
                    print(f"  {metric:16s} {slug:40s} (no local file)")
            else:
                board = download_leaderboard(api, slug)
                if board is not None and args.save_raw:
                    args.save_raw.mkdir(parents=True, exist_ok=True)
                    with (args.save_raw / f"{slug}.csv").open("w", newline="") as stream:
                        writer = csv.DictWriter(stream, fieldnames=list(board[0].keys()) if board else [])
                        writer.writeheader()
                        writer.writerows(board)
            if board is not None:
                print(f"  {metric:16s} {slug:40s} {len(board)} team(s)")
            boards[metric] = board
        tracks.append(build_track(track, spec, boards, config))

    generated = args.now or datetime.now(timezone.utc).isoformat(timespec="seconds")
    payload = json.dumps(
        {"schema": 1, "generated_at": generated, "source": "kaggle", "tracks": tracks},
        indent=1,
        sort_keys=False,
    ) + "\n"

    changed = True
    if args.out.exists():
        try:
            changed = material(json.loads(args.out.read_text())) != material(json.loads(payload))
        except json.JSONDecodeError:
            changed = True
    if not changed:
        print(f"no change; leaving {args.out} untouched")
        return 0

    write_atomic(args.out, payload)
    total = sum(len(t["rows"]) for t in tracks)
    print(f"wrote {args.out} ({args.out.stat().st_size:,} B, {total} team-rows across {len(tracks)} track(s))")

    if args.publish:
        repo = args.publish_repo or args.out.parent
        relative = args.out.resolve().relative_to(Path(repo).resolve())
        publish(Path(repo), relative, f"leaderboard: scores changed ({generated})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
